<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="schemas\**" />
    <EmbeddedResource Remove="schemas\**" />
    <None Remove="schemas\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="libs\libmseed.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VL.Core" Version="2024.6.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="libs\libmseed.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
