//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace VL.Earth.FDSN;
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
[System.Xml.Serialization.XmlRootAttribute("FDSNStationXML", Namespace="http://www.fdsn.org/xml/station/1", IsNullable=false)]
public partial class RootType {
    
    private string sourceField;
    
    private string senderField;
    
    private string moduleField;
    
    private string moduleURIField;
    
    private System.DateTime createdField;
    
    private NetworkType[] networkField;
    
    private System.Xml.XmlElement[] anyField;
    
    private decimal schemaVersionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public string Module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string ModuleURI {
        get {
            return this.moduleURIField;
        }
        set {
            this.moduleURIField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Network")]
    public NetworkType[] Network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class NetworkType : BaseNodeType {
    
    private OperatorType[] operatorField;
    
    private string totalNumberStationsField;
    
    private string selectedNumberStationsField;
    
    private StationType[] stationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operator")]
    public OperatorType[] Operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotalNumberStations {
        get {
            return this.totalNumberStationsField;
        }
        set {
            this.totalNumberStationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SelectedNumberStations {
        get {
            return this.selectedNumberStationsField;
        }
        set {
            this.selectedNumberStationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Station")]
    public StationType[] Station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class OperatorType {
    
    private string agencyField;
    
    private PersonType[] contactField;
    
    private string webSiteField;
    
    /// <remarks/>
    public string Agency {
        get {
            return this.agencyField;
        }
        set {
            this.agencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contact")]
    public PersonType[] Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string WebSite {
        get {
            return this.webSiteField;
        }
        set {
            this.webSiteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PersonType {
    
    private string[] nameField;
    
    private string[] agencyField;
    
    private string[] emailField;
    
    private PhoneNumberType[] phoneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public string[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Agency")]
    public string[] Agency {
        get {
            return this.agencyField;
        }
        set {
            this.agencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Email")]
    public string[] Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Phone")]
    public PhoneNumberType[] Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PhoneNumberType {
    
    private string countryCodeField;
    
    private string areaCodeField;
    
    private string phoneNumberField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string AreaCode {
        get {
            return this.areaCodeField;
        }
        set {
            this.areaCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DecimationType {
    
    private FrequencyType inputSampleRateField;
    
    private string factorField;
    
    private string offsetField;
    
    private FloatType delayField;
    
    private FloatType correctionField;
    
    /// <remarks/>
    public FrequencyType InputSampleRate {
        get {
            return this.inputSampleRateField;
        }
        set {
            this.inputSampleRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    public FloatType Delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    public FloatType Correction {
        get {
            return this.correctionField;
        }
        set {
            this.correctionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class FrequencyType : FloatType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SampleRateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FrequencyType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DistanceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DipType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AzimuthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeBaseType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeBaseType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VoltageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SecondType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class FloatType {
    
    private string unitField;
    
    private double plusErrorField;
    
    private bool plusErrorFieldSpecified;
    
    private double minusErrorField;
    
    private bool minusErrorFieldSpecified;
    
    private string measurementMethodField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double plusError {
        get {
            return this.plusErrorField;
        }
        set {
            this.plusErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool plusErrorSpecified {
        get {
            return this.plusErrorFieldSpecified;
        }
        set {
            this.plusErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double minusError {
        get {
            return this.minusErrorField;
        }
        set {
            this.minusErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minusErrorSpecified {
        get {
            return this.minusErrorFieldSpecified;
        }
        set {
            this.minusErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string measurementMethod {
        get {
            return this.measurementMethodField;
        }
        set {
            this.measurementMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class SampleRateType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DistanceType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DipType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class AzimuthType : FloatType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class LongitudeBaseType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class LongitudeType : LongitudeBaseType {
    
    private string datumField;
    
    public LongitudeType() {
        this.datumField = "WGS84";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    [System.ComponentModel.DefaultValueAttribute("WGS84")]
    public string datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class LatitudeBaseType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class LatitudeType : LatitudeBaseType {
    
    private string datumField;
    
    public LatitudeType() {
        this.datumField = "WGS84";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    [System.ComponentModel.DefaultValueAttribute("WGS84")]
    public string datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class AngleType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class VoltageType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class SecondType : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ResponseStageType {
    
    private object[] itemsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string numberField;
    
    private string resourceIdField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Coefficients", typeof(CoefficientsType))]
    [System.Xml.Serialization.XmlElementAttribute("Decimation", typeof(DecimationType))]
    [System.Xml.Serialization.XmlElementAttribute("FIR", typeof(FIRType))]
    [System.Xml.Serialization.XmlElementAttribute("PolesZeros", typeof(PolesZerosType))]
    [System.Xml.Serialization.XmlElementAttribute("Polynomial", typeof(PolynomialType))]
    [System.Xml.Serialization.XmlElementAttribute("ResponseList", typeof(ResponseListType))]
    [System.Xml.Serialization.XmlElementAttribute("StageGain", typeof(GainType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class CoefficientsType : BaseFilterType {
    
    private CoefficientsTypeCfTransferFunctionType cfTransferFunctionTypeField;
    
    private CoefficientsTypeNumerator[] numeratorField;
    
    private CoefficientsTypeDenominator[] denominatorField;
    
    /// <remarks/>
    public CoefficientsTypeCfTransferFunctionType CfTransferFunctionType {
        get {
            return this.cfTransferFunctionTypeField;
        }
        set {
            this.cfTransferFunctionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Numerator")]
    public CoefficientsTypeNumerator[] Numerator {
        get {
            return this.numeratorField;
        }
        set {
            this.numeratorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Denominator")]
    public CoefficientsTypeDenominator[] Denominator {
        get {
            return this.denominatorField;
        }
        set {
            this.denominatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public enum CoefficientsTypeCfTransferFunctionType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ANALOG (RADIANS/SECOND)")]
    ANALOGRADIANSSECOND,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("ANALOG (HERTZ)")]
    ANALOGHERTZ,
    
    /// <remarks/>
    DIGITAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public partial class CoefficientsTypeNumerator : FloatNoUnitType {
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class FloatNoUnitType {
    
    private double plusErrorField;
    
    private bool plusErrorFieldSpecified;
    
    private double minusErrorField;
    
    private bool minusErrorFieldSpecified;
    
    private string measurementMethodField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double plusError {
        get {
            return this.plusErrorField;
        }
        set {
            this.plusErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool plusErrorSpecified {
        get {
            return this.plusErrorFieldSpecified;
        }
        set {
            this.plusErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double minusError {
        get {
            return this.minusErrorField;
        }
        set {
            this.minusErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minusErrorSpecified {
        get {
            return this.minusErrorFieldSpecified;
        }
        set {
            this.minusErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string measurementMethod {
        get {
            return this.measurementMethodField;
        }
        set {
            this.measurementMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public partial class CoefficientsTypeDenominator : FloatNoUnitType {
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PolynomialType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseListType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CoefficientsType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FIRType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PolesZerosType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class BaseFilterType {
    
    private string descriptionField;
    
    private UnitsType inputUnitsField;
    
    private UnitsType outputUnitsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string resourceIdField;
    
    private string nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public UnitsType InputUnits {
        get {
            return this.inputUnitsField;
        }
        set {
            this.inputUnitsField = value;
        }
    }
    
    /// <remarks/>
    public UnitsType OutputUnits {
        get {
            return this.outputUnitsField;
        }
        set {
            this.outputUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class UnitsType {
    
    private string nameField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PolynomialType : BaseFilterType {
    
    private PolynomialTypeApproximationType approximationTypeField;
    
    private FrequencyType frequencyLowerBoundField;
    
    private FrequencyType frequencyUpperBoundField;
    
    private double approximationLowerBoundField;
    
    private double approximationUpperBoundField;
    
    private double maximumErrorField;
    
    private PolynomialTypeCoefficient[] coefficientField;
    
    public PolynomialType() {
        this.approximationTypeField = PolynomialTypeApproximationType.MACLAURIN;
    }
    
    /// <remarks/>
    public PolynomialTypeApproximationType ApproximationType {
        get {
            return this.approximationTypeField;
        }
        set {
            this.approximationTypeField = value;
        }
    }
    
    /// <remarks/>
    public FrequencyType FrequencyLowerBound {
        get {
            return this.frequencyLowerBoundField;
        }
        set {
            this.frequencyLowerBoundField = value;
        }
    }
    
    /// <remarks/>
    public FrequencyType FrequencyUpperBound {
        get {
            return this.frequencyUpperBoundField;
        }
        set {
            this.frequencyUpperBoundField = value;
        }
    }
    
    /// <remarks/>
    public double ApproximationLowerBound {
        get {
            return this.approximationLowerBoundField;
        }
        set {
            this.approximationLowerBoundField = value;
        }
    }
    
    /// <remarks/>
    public double ApproximationUpperBound {
        get {
            return this.approximationUpperBoundField;
        }
        set {
            this.approximationUpperBoundField = value;
        }
    }
    
    /// <remarks/>
    public double MaximumError {
        get {
            return this.maximumErrorField;
        }
        set {
            this.maximumErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Coefficient")]
    public PolynomialTypeCoefficient[] Coefficient {
        get {
            return this.coefficientField;
        }
        set {
            this.coefficientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public enum PolynomialTypeApproximationType {
    
    /// <remarks/>
    MACLAURIN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PolynomialTypeCoefficient : FloatNoUnitType {
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ResponseListType : BaseFilterType {
    
    private ResponseListElementType[] responseListElementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResponseListElement")]
    public ResponseListElementType[] ResponseListElement {
        get {
            return this.responseListElementField;
        }
        set {
            this.responseListElementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ResponseListElementType {
    
    private FrequencyType frequencyField;
    
    private FloatType amplitudeField;
    
    private AngleType phaseField;
    
    /// <remarks/>
    public FrequencyType Frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public FloatType Amplitude {
        get {
            return this.amplitudeField;
        }
        set {
            this.amplitudeField = value;
        }
    }
    
    /// <remarks/>
    public AngleType Phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class FIRType : BaseFilterType {
    
    private FIRTypeSymmetry symmetryField;
    
    private FIRTypeNumeratorCoefficient[] numeratorCoefficientField;
    
    /// <remarks/>
    public FIRTypeSymmetry Symmetry {
        get {
            return this.symmetryField;
        }
        set {
            this.symmetryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NumeratorCoefficient")]
    public FIRTypeNumeratorCoefficient[] NumeratorCoefficient {
        get {
            return this.numeratorCoefficientField;
        }
        set {
            this.numeratorCoefficientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public enum FIRTypeSymmetry {
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    EVEN,
    
    /// <remarks/>
    ODD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public partial class FIRTypeNumeratorCoefficient {
    
    private string iField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PolesZerosType : BaseFilterType {
    
    private PolesZerosTypePzTransferFunctionType pzTransferFunctionTypeField;
    
    private double normalizationFactorField;
    
    private FrequencyType normalizationFrequencyField;
    
    private PoleZeroType[] zeroField;
    
    private PoleZeroType[] poleField;
    
    public PolesZerosType() {
        this.normalizationFactorField = 1D;
    }
    
    /// <remarks/>
    public PolesZerosTypePzTransferFunctionType PzTransferFunctionType {
        get {
            return this.pzTransferFunctionTypeField;
        }
        set {
            this.pzTransferFunctionTypeField = value;
        }
    }
    
    /// <remarks/>
    public double NormalizationFactor {
        get {
            return this.normalizationFactorField;
        }
        set {
            this.normalizationFactorField = value;
        }
    }
    
    /// <remarks/>
    public FrequencyType NormalizationFrequency {
        get {
            return this.normalizationFrequencyField;
        }
        set {
            this.normalizationFrequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Zero")]
    public PoleZeroType[] Zero {
        get {
            return this.zeroField;
        }
        set {
            this.zeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pole")]
    public PoleZeroType[] Pole {
        get {
            return this.poleField;
        }
        set {
            this.poleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public enum PolesZerosTypePzTransferFunctionType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LAPLACE (RADIANS/SECOND)")]
    LAPLACERADIANSSECOND,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LAPLACE (HERTZ)")]
    LAPLACEHERTZ,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DIGITAL (Z-TRANSFORM)")]
    DIGITALZTRANSFORM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class PoleZeroType {
    
    private FloatNoUnitType realField;
    
    private FloatNoUnitType imaginaryField;
    
    private string numberField;
    
    /// <remarks/>
    public FloatNoUnitType Real {
        get {
            return this.realField;
        }
        set {
            this.realField = value;
        }
    }
    
    /// <remarks/>
    public FloatNoUnitType Imaginary {
        get {
            return this.imaginaryField;
        }
        set {
            this.imaginaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SensitivityType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class GainType {
    
    private double valueField;
    
    private double frequencyField;
    
    /// <remarks/>
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public double Frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class SensitivityType : GainType {
    
    private UnitsType inputUnitsField;
    
    private UnitsType outputUnitsField;
    
    private double frequencyStartField;
    
    private double frequencyEndField;
    
    private double frequencyDBVariationField;
    
    /// <remarks/>
    public UnitsType InputUnits {
        get {
            return this.inputUnitsField;
        }
        set {
            this.inputUnitsField = value;
        }
    }
    
    /// <remarks/>
    public UnitsType OutputUnits {
        get {
            return this.outputUnitsField;
        }
        set {
            this.outputUnitsField = value;
        }
    }
    
    /// <remarks/>
    public double FrequencyStart {
        get {
            return this.frequencyStartField;
        }
        set {
            this.frequencyStartField = value;
        }
    }
    
    /// <remarks/>
    public double FrequencyEnd {
        get {
            return this.frequencyEndField;
        }
        set {
            this.frequencyEndField = value;
        }
    }
    
    /// <remarks/>
    public double FrequencyDBVariation {
        get {
            return this.frequencyDBVariationField;
        }
        set {
            this.frequencyDBVariationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ResponseType {
    
    private object itemField;
    
    private ResponseStageType[] stageField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string resourceIdField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InstrumentPolynomial", typeof(PolynomialType))]
    [System.Xml.Serialization.XmlElementAttribute("InstrumentSensitivity", typeof(SensitivityType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Stage")]
    public ResponseStageType[] Stage {
        get {
            return this.stageField;
        }
        set {
            this.stageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class SampleRateRatioType {
    
    private string numberSamplesField;
    
    private string numberSecondsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberSamples {
        get {
            return this.numberSamplesField;
        }
        set {
            this.numberSamplesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberSeconds {
        get {
            return this.numberSecondsField;
        }
        set {
            this.numberSecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ExternalReferenceType {
    
    private string uRIField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class EquipmentType {
    
    private string typeField;
    
    private string descriptionField;
    
    private string manufacturerField;
    
    private string vendorField;
    
    private string modelField;
    
    private string serialNumberField;
    
    private System.DateTime installationDateField;
    
    private bool installationDateFieldSpecified;
    
    private System.DateTime removalDateField;
    
    private bool removalDateFieldSpecified;
    
    private System.DateTime[] calibrationDateField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string resourceIdField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    public string Model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime InstallationDate {
        get {
            return this.installationDateField;
        }
        set {
            this.installationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InstallationDateSpecified {
        get {
            return this.installationDateFieldSpecified;
        }
        set {
            this.installationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime RemovalDate {
        get {
            return this.removalDateField;
        }
        set {
            this.removalDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RemovalDateSpecified {
        get {
            return this.removalDateFieldSpecified;
        }
        set {
            this.removalDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CalibrationDate")]
    public System.DateTime[] CalibrationDate {
        get {
            return this.calibrationDateField;
        }
        set {
            this.calibrationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class SiteType {
    
    private string nameField;
    
    private string descriptionField;
    
    private string townField;
    
    private string countyField;
    
    private string regionField;
    
    private string countryField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    /// <remarks/>
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DataAvailabilitySpanType {
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private string numberSegmentsField;
    
    private decimal maximumTimeTearField;
    
    private bool maximumTimeTearFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string numberSegments {
        get {
            return this.numberSegmentsField;
        }
        set {
            this.numberSegmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumTimeTear {
        get {
            return this.maximumTimeTearField;
        }
        set {
            this.maximumTimeTearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumTimeTearSpecified {
        get {
            return this.maximumTimeTearFieldSpecified;
        }
        set {
            this.maximumTimeTearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DataAvailabilityExtentType {
    
    private System.DateTime startField;
    
    private System.DateTime endField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class DataAvailabilityType {
    
    private DataAvailabilityExtentType extentField;
    
    private DataAvailabilitySpanType[] spanField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public DataAvailabilityExtentType Extent {
        get {
            return this.extentField;
        }
        set {
            this.extentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Span")]
    public DataAvailabilitySpanType[] Span {
        get {
            return this.spanField;
        }
        set {
            this.spanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class CommentType {
    
    private string valueField;
    
    private System.DateTime beginEffectiveTimeField;
    
    private bool beginEffectiveTimeFieldSpecified;
    
    private System.DateTime endEffectiveTimeField;
    
    private bool endEffectiveTimeFieldSpecified;
    
    private PersonType[] authorField;
    
    private string idField;
    
    private string subjectField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime BeginEffectiveTime {
        get {
            return this.beginEffectiveTimeField;
        }
        set {
            this.beginEffectiveTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BeginEffectiveTimeSpecified {
        get {
            return this.beginEffectiveTimeFieldSpecified;
        }
        set {
            this.beginEffectiveTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EndEffectiveTime {
        get {
            return this.endEffectiveTimeField;
        }
        set {
            this.endEffectiveTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndEffectiveTimeSpecified {
        get {
            return this.endEffectiveTimeFieldSpecified;
        }
        set {
            this.endEffectiveTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Author")]
    public PersonType[] Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class IdentifierType {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetworkType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class BaseNodeType {
    
    private string descriptionField;
    
    private IdentifierType[] identifierField;
    
    private CommentType[] commentField;
    
    private DataAvailabilityType dataAvailabilityField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string codeField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    private string sourceIDField;
    
    private RestrictedStatusType restrictedStatusField;
    
    private bool restrictedStatusFieldSpecified;
    
    private string alternateCodeField;
    
    private string historicalCodeField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Identifier")]
    public IdentifierType[] Identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Comment")]
    public CommentType[] Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public DataAvailabilityType DataAvailability {
        get {
            return this.dataAvailabilityField;
        }
        set {
            this.dataAvailabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string sourceID {
        get {
            return this.sourceIDField;
        }
        set {
            this.sourceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RestrictedStatusType restrictedStatus {
        get {
            return this.restrictedStatusField;
        }
        set {
            this.restrictedStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool restrictedStatusSpecified {
        get {
            return this.restrictedStatusFieldSpecified;
        }
        set {
            this.restrictedStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alternateCode {
        get {
            return this.alternateCodeField;
        }
        set {
            this.alternateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string historicalCode {
        get {
            return this.historicalCodeField;
        }
        set {
            this.historicalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public enum RestrictedStatusType {
    
    /// <remarks/>
    open,
    
    /// <remarks/>
    closed,
    
    /// <remarks/>
    partial,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ChannelType : BaseNodeType {
    
    private ExternalReferenceType[] externalReferenceField;
    
    private LatitudeType latitudeField;
    
    private LongitudeType longitudeField;
    
    private DistanceType elevationField;
    
    private DistanceType depthField;
    
    private AzimuthType azimuthField;
    
    private DipType dipField;
    
    private FloatType waterLevelField;
    
    private ChannelTypeType[] typeField;
    
    private SampleRateType sampleRateField;
    
    private SampleRateRatioType sampleRateRatioField;
    
    private ChannelTypeClockDrift clockDriftField;
    
    private UnitsType calibrationUnitsField;
    
    private EquipmentType sensorField;
    
    private EquipmentType preAmplifierField;
    
    private EquipmentType dataLoggerField;
    
    private EquipmentType[] equipmentField;
    
    private ResponseType responseField;
    
    private string locationCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference")]
    public ExternalReferenceType[] ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
    
    /// <remarks/>
    public LatitudeType Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public LongitudeType Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public DistanceType Elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    public DistanceType Depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    public AzimuthType Azimuth {
        get {
            return this.azimuthField;
        }
        set {
            this.azimuthField = value;
        }
    }
    
    /// <remarks/>
    public DipType Dip {
        get {
            return this.dipField;
        }
        set {
            this.dipField = value;
        }
    }
    
    /// <remarks/>
    public FloatType WaterLevel {
        get {
            return this.waterLevelField;
        }
        set {
            this.waterLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Type")]
    public ChannelTypeType[] Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public SampleRateType SampleRate {
        get {
            return this.sampleRateField;
        }
        set {
            this.sampleRateField = value;
        }
    }
    
    /// <remarks/>
    public SampleRateRatioType SampleRateRatio {
        get {
            return this.sampleRateRatioField;
        }
        set {
            this.sampleRateRatioField = value;
        }
    }
    
    /// <remarks/>
    public ChannelTypeClockDrift ClockDrift {
        get {
            return this.clockDriftField;
        }
        set {
            this.clockDriftField = value;
        }
    }
    
    /// <remarks/>
    public UnitsType CalibrationUnits {
        get {
            return this.calibrationUnitsField;
        }
        set {
            this.calibrationUnitsField = value;
        }
    }
    
    /// <remarks/>
    public EquipmentType Sensor {
        get {
            return this.sensorField;
        }
        set {
            this.sensorField = value;
        }
    }
    
    /// <remarks/>
    public EquipmentType PreAmplifier {
        get {
            return this.preAmplifierField;
        }
        set {
            this.preAmplifierField = value;
        }
    }
    
    /// <remarks/>
    public EquipmentType DataLogger {
        get {
            return this.dataLoggerField;
        }
        set {
            this.dataLoggerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Equipment")]
    public EquipmentType[] Equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    public ResponseType Response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locationCode {
        get {
            return this.locationCodeField;
        }
        set {
            this.locationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public enum ChannelTypeType {
    
    /// <remarks/>
    TRIGGERED,
    
    /// <remarks/>
    CONTINUOUS,
    
    /// <remarks/>
    HEALTH,
    
    /// <remarks/>
    GEOPHYSICAL,
    
    /// <remarks/>
    WEATHER,
    
    /// <remarks/>
    FLAG,
    
    /// <remarks/>
    SYNTHESIZED,
    
    /// <remarks/>
    INPUT,
    
    /// <remarks/>
    EXPERIMENTAL,
    
    /// <remarks/>
    MAINTENANCE,
    
    /// <remarks/>
    BEAM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fdsn.org/xml/station/1")]
public partial class ChannelTypeClockDrift : FloatType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fdsn.org/xml/station/1")]
public partial class StationType : BaseNodeType {
    
    private LatitudeType latitudeField;
    
    private LongitudeType longitudeField;
    
    private DistanceType elevationField;
    
    private SiteType siteField;
    
    private FloatType waterLevelField;
    
    private string vaultField;
    
    private string geologyField;
    
    private EquipmentType[] equipmentField;
    
    private OperatorType[] operatorField;
    
    private System.DateTime creationDateField;
    
    private bool creationDateFieldSpecified;
    
    private System.DateTime terminationDateField;
    
    private bool terminationDateFieldSpecified;
    
    private string totalNumberChannelsField;
    
    private string selectedNumberChannelsField;
    
    private ExternalReferenceType[] externalReferenceField;
    
    private ChannelType[] channelField;
    
    /// <remarks/>
    public LatitudeType Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public LongitudeType Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public DistanceType Elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    public SiteType Site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public FloatType WaterLevel {
        get {
            return this.waterLevelField;
        }
        set {
            this.waterLevelField = value;
        }
    }
    
    /// <remarks/>
    public string Vault {
        get {
            return this.vaultField;
        }
        set {
            this.vaultField = value;
        }
    }
    
    /// <remarks/>
    public string Geology {
        get {
            return this.geologyField;
        }
        set {
            this.geologyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Equipment")]
    public EquipmentType[] Equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operator")]
    public OperatorType[] Operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreationDateSpecified {
        get {
            return this.creationDateFieldSpecified;
        }
        set {
            this.creationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TerminationDate {
        get {
            return this.terminationDateField;
        }
        set {
            this.terminationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TerminationDateSpecified {
        get {
            return this.terminationDateFieldSpecified;
        }
        set {
            this.terminationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotalNumberChannels {
        get {
            return this.totalNumberChannelsField;
        }
        set {
            this.totalNumberChannelsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SelectedNumberChannels {
        get {
            return this.selectedNumberChannelsField;
        }
        set {
            this.selectedNumberChannelsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalReference")]
    public ExternalReferenceType[] ExternalReference {
        get {
            return this.externalReferenceField;
        }
        set {
            this.externalReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Channel")]
    public ChannelType[] Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
}
